### ISSUE TITLE
Update patch to v6.2.0

### ISSUE THREAD

**Issue by igrekster** [64kramsystem/qemu-pinning#37]
Any plans to update the patch to work with v6.2.0 ?

**Comment by 64kramsystem** [comment]
Hello!

Unfortunately I haven't any plans to do so (for reference, the README explains [the project status](https://github.com/64kramsystem/qemu-pinning#status)).

I accept PRs, though!

**Comment by igrekster** [comment]
Fair enough. Having looked at the recent changes -- I agree it would be tedious to support it in the future.
I went with a workaround instead (tested on v6.2.0 on Gentoo):

```python
import time
import sys

from subprocess import call
from qemu.qmp import QEMUMonitorProtocol

qmp = QEMUMonitorProtocol(sys.argv[1])

while True:
    try:
        print("Connecting to {}".format(sys.argv[1]))
        qmp.connect()
        break
    except Exception as e:
        print('Failed to connect to QEMU: {}'.format(e))
        time.sleep(0.1)

for cpu in qmp.command('query-cpus-fast'):
    tid = cpu['thread-id']
    cpuidx = cpu['cpu-index']
    try:
        call(['taskset', '-pc', str(cpuidx), str(tid)])
    except OSError as e:
        print('Failed to pin vCPU{}: {}'.format(cpuidx, e))
```

```bash
/usr/bin/python3 ~/bin/qemu-pin-vcpu.py /tmp/.qmp-sock &
qemu-system-x86_64 -qmp unix:/tmp/.qmp-sock,server=on,wait=off ...
```

**Comment by 64kramsystem** [comment]
> Fair enough. Having looked at the recent changes -- I agree it would be tedious to support it in the future. I went with a workaround instead (tested on v6.2.0 on Gentoo):
> 
> ```python
> import time
> import sys
> 
> from subprocess import call
> from qemu.qmp import QEMUMonitorProtocol
> 
> qmp = QEMUMonitorProtocol(sys.argv[1])
> 
> while True:
>     try:
>         print("Connecting to {}".format(sys.argv[1]))
>         qmp.connect()
>         break
>     except Exception as e:
>         print('Failed to connect to QEMU: {}'.format(e))
>         time.sleep(0.1)
> 
> for cpu in qmp.command('query-cpus-fast'):
>     tid = cpu['thread-id']
>     cpuidx = cpu['cpu-index']
>     try:
>         call(['taskset', '-pc', str(cpuidx), str(tid)])
>     except OSError as e:
>         print('Failed to pin vCPU{}: {}'.format(cpuidx, e))
> ```
> 
> ```shell
> /usr/bin/python3 ~/bin/qemu-pin-vcpu.py /tmp/.qmp-sock &
> qemu-system-x86_64 -qmp unix:/tmp/.qmp-sock,server=on,wait=off ...
> ```

Thanks for the script! I'm going to add it to the wiki, and reference it in the README.
