### ISSUE TITLE
qemu 8.0  build error

### ISSUE THREAD

**Issue by aiminickwong** [64kramsystem/qemu-pinning#42]
I can not build with this except newest qemu 8.0 release edition

**Comment by 64kramsystem** [comment]
> I can not build with this except newest qemu 8.0 release edition

Hello!

Sorry, I don't understand the statement. The patch on the master branch is intended to work on the latest release, and not the former.
If you want to patch older QEMU releases, you'll find the patches on the branches.

Feel free to reopen the issue if this doesn't solve your problem :smile:
